### ISSUE TITLE
Error after adding your package

### ISSUE THREAD

**Issue by atheriault** [pascoual/meteor-pdfkitx#1]
I have been working on my webapp, everything runs smooth, Now I went to add your package in and restarted meteor and am now getting the following errors:

Uncaught TypeError: Cannot read property 'PDFDocument' of undefined(anonymous function) @ global-imports.js?d74a79f677ad7ab83416fb22ea02da5211a9a6e3:15
template.carriersTemplate.js?9212e0eff92f5316280ffb59bee980ede724baf9:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.carriersTemplate.js?9212e0eff92f5316280ffb59bee980ede724baf9:2(anonymous function) @ template.carriersTemplate.js?9212e0eff92f5316280ffb59bee980ede724baf9:97
template.chargesTemplate.js?2e412fe0d314c4316455959e0ddf48249f61627f:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.chargesTemplate.js?2e412fe0d314c4316455959e0ddf48249f61627f:2(anonymous function) @ template.chargesTemplate.js?2e412fe0d314c4316455959e0ddf48249f61627f:100
template.confirmCustModal.js?226b8eae7bc1a9df7b95ea76d02d5dbbe4cd0148:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.confirmCustModal.js?226b8eae7bc1a9df7b95ea76d02d5dbbe4cd0148:2(anonymous function) @ template.confirmCustModal.js?226b8eae7bc1a9df7b95ea76d02d5dbbe4cd0148:27
template.customerCreateTemplate.js?2982be9972252edbb76df0cf95a6774bfa4995ab:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.customerCreateTemplate.js?2982be9972252edbb76df0cf95a6774bfa4995ab:2(anonymous function) @ template.customerCreateTemplate.js?2982be9972252edbb76df0cf95a6774bfa4995ab:91
template.customerTemplate.js?eb94c2acf4d3e890e96fa7f460ce19c733ecae07:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.customerTemplate.js?eb94c2acf4d3e890e96fa7f460ce19c733ecae07:2(anonymous function) @ template.customerTemplate.js?eb94c2acf4d3e890e96fa7f460ce19c733ecae07:19
template.driversTemplate.js?4398d8446a0fc930edc3d87364cfb8854c2a0010:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.driversTemplate.js?4398d8446a0fc930edc3d87364cfb8854c2a0010:2(anonymous function) @ template.driversTemplate.js?4398d8446a0fc930edc3d87364cfb8854c2a0010:173
template.loginFormTemplate.js?884bc393739de1d823c5aa2dfacb4310077428ec:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.loginFormTemplate.js?884bc393739de1d823c5aa2dfacb4310077428ec:2(anonymous function) @ template.loginFormTemplate.js?884bc393739de1d823c5aa2dfacb4310077428ec:8
template.navBarTemplate.js?3f3adbf09b5ddf24f31a37aa25544402e046d7e3:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.navBarTemplate.js?3f3adbf09b5ddf24f31a37aa25544402e046d7e3:2(anonymous function) @ template.navBarTemplate.js?3f3adbf09b5ddf24f31a37aa25544402e046d7e3:97
template.orderEntryCustTabTemplate.js?d3e2e192f6f22156b877ac0f8745e7ed1baaf0ce:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.orderEntryCustTabTemplate.js?d3e2e192f6f22156b877ac0f8745e7ed1baaf0ce:2(anonymous function) @ template.orderEntryCustTabTemplate.js?d3e2e192f6f22156b877ac0f8745e7ed1baaf0ce:392
template.orderEntryDELTabTemplate.js?de8bbe633c9012d5584704601870d220b5b9029f:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.orderEntryDELTabTemplate.js?de8bbe633c9012d5584704601870d220b5b9029f:2(anonymous function) @ template.orderEntryDELTabTemplate.js?de8bbe633c9012d5584704601870d220b5b9029f:121
template.orderEntryDispTabTemplate.js?57c389287528ea8d3001d730497ff1fdc71610a1:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.orderEntryDispTabTemplate.js?57c389287528ea8d3001d730497ff1fdc71610a1:2(anonymous function) @ template.orderEntryDispTabTemplate.js?57c389287528ea8d3001d730497ff1fdc71610a1:485
template.orderEntryPUTabTemplate.js?6340859e6571e64388db22ff08ac064b24123fa2:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.orderEntryPUTabTemplate.js?6340859e6571e64388db22ff08ac064b24123fa2:2(anonymous function) @ template.orderEntryPUTabTemplate.js?6340859e6571e64388db22ff08ac064b24123fa2:121
template.orderEntryTemplate.js?5ffabcbe699c1967480e96e6c6bd6b44c0f83bc1:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.orderEntryTemplate.js?5ffabcbe699c1967480e96e6c6bd6b44c0f83bc1:2(anonymous function) @ template.orderEntryTemplate.js?5ffabcbe699c1967480e96e6c6bd6b44c0f83bc1:36
template.testfiles.js?7105eb509a974dde264bc85b99e7634bdd181668:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.testfiles.js?7105eb509a974dde264bc85b99e7634bdd181668:2(anonymous function) @ template.testfiles.js?7105eb509a974dde264bc85b99e7634bdd181668:8
template.trailersTemplate.js?61f04fa835e17a9d8e1f4ff9e514534ad5db7c21:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.trailersTemplate.js?61f04fa835e17a9d8e1f4ff9e514534ad5db7c21:2(anonymous function) @ template.trailersTemplate.js?61f04fa835e17a9d8e1f4ff9e514534ad5db7c21:95
template.trucksTemplate.js?27e616b71967d9fa99d5c0c9526615a5046b99fe:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.trucksTemplate.js?27e616b71967d9fa99d5c0c9526615a5046b99fe:2(anonymous function) @ template.trucksTemplate.js?27e616b71967d9fa99d5c0c9526615a5046b99fe:109
template.yardsTemplate.js?34672138b0a775451d51d56f2123a229116d818a:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.yardsTemplate.js?34672138b0a775451d51d56f2123a229116d818a:2(anonymous function) @ template.yardsTemplate.js?34672138b0a775451d51d56f2123a229116d818a:106
template.layoutTemplate.js?ba8bd0e6c0d92b68dd14d7c926df83e8464d7cbb:2 Uncaught ReferenceError: Template is not defined(anonymous function) @ template.layoutTemplate.js?ba8bd0e6c0d92b68dd14d7c926df83e8464d7cbb:2(anonymous function) @ template.layoutTemplate.js?ba8bd0e6c0d92b68dd14d7c926df83e8464d7cbb:14
carriersController.js?7df175618e81d7585cc5df07fa3d3aef8bd098cc:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ carriersController.js?7df175618e81d7585cc5df07fa3d3aef8bd098cc:1(anonymous function) @ carriersController.js?7df175618e81d7585cc5df07fa3d3aef8bd098cc:167
chargesController.js?c501470c7a7394e48153c8cc1e0bfea2e7b303c8:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ chargesController.js?c501470c7a7394e48153c8cc1e0bfea2e7b303c8:1(anonymous function) @ chargesController.js?c501470c7a7394e48153c8cc1e0bfea2e7b303c8:157
customerController.js?d56445bd86fb801da5404fc504d5f449f9e24266:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ customerController.js?d56445bd86fb801da5404fc504d5f449f9e24266:1(anonymous function) @ customerController.js?d56445bd86fb801da5404fc504d5f449f9e24266:362
driversController.js?0267ab18177ec3c353cd6081d797828df943d610:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ driversController.js?0267ab18177ec3c353cd6081d797828df943d610:1(anonymous function) @ driversController.js?0267ab18177ec3c353cd6081d797828df943d610:598
loginFormController.js?d3acd2bb31883e6e2174bd2cbef4378f021ca20b:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ loginFormController.js?d3acd2bb31883e6e2174bd2cbef4378f021ca20b:1(anonymous function) @ loginFormController.js?d3acd2bb31883e6e2174bd2cbef4378f021ca20b:45
navBarController.js?305f304fbe723e825b4c2c21e368ef1fb3d15079:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ navBarController.js?305f304fbe723e825b4c2c21e368ef1fb3d15079:1(anonymous function) @ navBarController.js?305f304fbe723e825b4c2c21e368ef1fb3d15079:18
orderEntryController.js?61a17b9f50328adc5ae2aa12e493558ba3f637ba:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ orderEntryController.js?61a17b9f50328adc5ae2aa12e493558ba3f637ba:1(anonymous function) @ orderEntryController.js?61a17b9f50328adc5ae2aa12e493558ba3f637ba:2038
testfiles.js?7e7cb08cac33423120d5e006a8759eda90bb1e59:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ testfiles.js?7e7cb08cac33423120d5e006a8759eda90bb1e59:1(anonymous function) @ testfiles.js?7e7cb08cac33423120d5e006a8759eda90bb1e59:42
trailersController.js?f92aa60b6a993905fc220e22089379a9a0099cd2:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ trailersController.js?f92aa60b6a993905fc220e22089379a9a0099cd2:1(anonymous function) @ trailersController.js?f92aa60b6a993905fc220e22089379a9a0099cd2:158
trucksController.js?fadac36777cc4aa4e75e60c983d52d69a6b067fb:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ trucksController.js?fadac36777cc4aa4e75e60c983d52d69a6b067fb:1(anonymous function) @ trucksController.js?fadac36777cc4aa4e75e60c983d52d69a6b067fb:177
yardsController.js?72121bbde2ac0e5589d625dad6534c25312c3df3:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ yardsController.js?72121bbde2ac0e5589d625dad6534c25312c3df3:1(anonymous function) @ yardsController.js?72121bbde2ac0e5589d625dad6534c25312c3df3:176
routerController.js?3e6175757455d5cdcea9a8fc795ecee1f5118538:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ routerController.js?3e6175757455d5cdcea9a8fc795ecee1f5118538:1(anonymous function) @ routerController.js?3e6175757455d5cdcea9a8fc795ecee1f5118538:100
common.js:90 Uncaught ReferenceError: _ is not definedMongol.detectCollections @ common.js:90(anonymous function) @ main.js:9runStartupCallbacks @ startup_client.js:30ready @ startup_client.js:32
debug.js:41 Exception in defer callback: ReferenceError: Spacebars is not defined
    at http://localhost:3000/packages/meteortoys_toykit.js?869f3f822b68a0206806ace5cd094e633be04612:53:12
    at null.<anonymous> (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2626:44)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1865:18
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1864:29
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12)
    at viewAutorun (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1863:18)
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:36)
    at new Tracker.Computation (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:243:10)
    at Object.Tracker.autorun (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:566:11)
debug.js:41 Exception in defer callback: ReferenceError: Spacebars is not defined
    at Template.Mongol.Blaze.If.HTML.DIV.id (http://localhost:3000/packages/msavin_mongol.js?7ab8394418b37a6d82d949bc96730329514fa7ca:1084:12)
    at null.<anonymous> (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2626:44)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1865:18
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1864:29
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12)
    at viewAutorun (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1863:18)
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:36)
    at new Tracker.Computation (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:243:10)
    at Object.Tracker.autorun (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:566:11)
default_layout.html:5 Uncaught ReferenceError: Spacebars is not defined

Now Not a single line of code has been changed.  I removed the package and everything works fine again. Re-added it and same set of errors.  I really like the look of this package and would like to use it.  Any help here is greatly appreciated.

**Comment by rudza** [comment]
Similar issue here too!

**Comment by pascoual** [comment]
No news since 2015. Closing.
